### ISSUE TITLE
Error: 'Video.js' does not match the corresponding name on disk: './src/components/video.js'

### ISSUE THREAD

**Issue by tvotan** [jamalag/webrtc-part-7#5]
Hi @jamalag ,

when I pull the repo on my Mac and run the commands:
1. `$ yarn install`
2. `$ yarn build`
3. `$ yarn start`

I get an error message:
`Cannot find file: 'Video.js' does not match the corresponding name on disk: './src/components/video.js'.`

Can you help me solving this? Obviously it must be a problem with video.js . Here is a screenshot when I run the react app in my browser:
<img width="1035" alt="Screenshot 2020-08-03 at 13 08 08" src="https://user-images.githubusercontent.com/39995527/89177048-ec9aea00-d58a-11ea-899a-bf190a0966a4.png">

Cheers

**Comment by jamalag** [comment]
Hi @tvotan 
That's a typo in videos.js.
The import for video component in videos.js should be in small caps - I have changed it in the code.

import React, {Component} from 'react'
import Video from './video' // <-------- changed to './video' from './Video'
