### ISSUE TITLE
chat is not working

### ISSUE THREAD

**Issue by itsg2jakhmola** [jamalag/webrtc-part-7#7]
Chat message is not working, it does work when refreshes the page, realtime it is not working when 3-4 person connected.

**Comment by jamalag** [comment]
Are you getting any errors?

**Comment by itsg2jakhmola** [comment]
No error log deducted, i guess emit is not happening properly

**Comment by jamalag** [comment]
I will test the repo again but did you follow the video series and write the code yourself?

**Comment by itsg2jakhmola** [comment]
I just use the github code, install dependancy and run the project.

**Comment by jamalag** [comment]
Actually everything works fine from my end but may be there is a difference in the code between repo and my local. I will compare and upload if necessary and let you know. Or if you have already resolved the issue you may wish to highlight it here. Thanks.

**Comment by arsalanator** [comment]
the web app is working fine. the mobile app crashes as soon as it loads

**Comment by jamalag** [comment]
mobile App: is it iOS or Android? 
... and is it the first time you are running the mobile App?

**Comment by arsalanator** [comment]
> mobile App: is it iOS or Android?
> ... and is it the first time you are running the mobile App?

Android. I am running your mobile app for first time, but I have developed lots of apps before

**Comment by jamalag** [comment]
I think back in Part 4 of the video series, there was a discussion on the issue of Android crashing and one viewer solved it. Let me look fo the discussion and share it.

**Comment by arsalanator** [comment]
> I think back in Part 4 of the video series, there was a discussion on the issue of Android crashing and one viewer solved it. Let me look fo the discussion and share it.

I see, but it's part 7 we are at so most probably it would have been fixed. Waiting for you check out part 7 ie this repo and let us know. By the way great work there !!! :)

**Comment by jamalag** [comment]
...
in the link Rahul indicates he had solved the crashing issue in Android (his own repo but I think he forked video 4 code)
https://github.com/rahulbtops/webrtc

in this link he is discussing issue with running in Android browser
https://github.com/jamalag/webrtc-part-5-React-Hooks/issues/2

**Comment by arsalanator** [comment]
> ...
> in the link Rahul indicates he had solved the crashing issue in Android (his own repo but I think he forked video 2 code)
> https://github.com/rahulbtops/webrtc
> 
> in this link he is discussing issue with running in Android browser
> [jamalag/webrtc-part-5-React-Hooks#2](https://github.com/jamalag/webrtc-part-5-React-Hooks/issues/2)

Ok great let me try this one. If it works or doesn't, in both cases I will let you know. Thanks a lot

**Comment by jamalag** [comment]
> > I think back in Part 4 of the video series, there was a discussion on the issue of Android crashing and one viewer solved it. Let me look fo the discussion and share it.
> 
> I see, but it's part 7 we are at so most probably it would have been fixed. Waiting for you check out part 7 ie this repo and let us know. By the way great work there !!! :)

Well, not really because I think I moved on before Rahul raising the issue - and you will notice I mostly used iOS to demo

**Comment by arsalanator** [comment]
> > > I think back in Part 4 of the video series, there was a discussion on the issue of Android crashing and one viewer solved it. Let me look fo the discussion and share it.
> > 
> > 
> > I see, but it's part 7 we are at so most probably it would have been fixed. Waiting for you check out part 7 ie this repo and let us know. By the way great work there !!! :)
> 
> Well, not really because I think I moved on before Rahul raising the issue - and you will notice I mostly used iOS to demo

Yeah you used iOS and web. Let me try the other one you linked and will let you know.

**Comment by arsalanator** [comment]
> ...
> in the link Rahul indicates he had solved the crashing issue in Android (his own repo but I think he forked video 4 code)
> https://github.com/rahulbtops/webrtc
> 
> in this link he is discussing issue with running in Android browser
> [jamalag/webrtc-part-5-React-Hooks#2](https://github.com/jamalag/webrtc-part-5-React-Hooks/issues/2)

I have tested it on Android, yes it works. Thanks a lot for your support and patience. And great work by the way JazakAllah

**Comment by jamalag** [comment]
> > ...
> > in the link Rahul indicates he had solved the crashing issue in Android (his own repo but I think he forked video 4 code)
> > https://github.com/rahulbtops/webrtc
> > in this link he is discussing issue with running in Android browser
> > [jamalag/webrtc-part-5-React-Hooks#2](https://github.com/jamalag/webrtc-part-5-React-Hooks/issues/2)
> 
> I have tested it on Android, yes it works. Thanks a lot for your support and patience. And great work by the way JazakAllah

wa-iyyak!
